server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  application:
    name: tourism-services
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
      cache:
        use_second_level_cache: false
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      booking: booking-topic
    consumer:
      group-id: booking-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


aws:
  region: us-east-2
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
  sqs:
    queue:
      name: bookings-dev
      url: ${AWS_SQS_QUEUE_URL}

encrypt:
  password: ${ENCRYPT_PASSWORD}

session:
  client-secret: ${SESSION_CLIENT_SECRET}
  access-token-expiration-time: 15
  refresh-token-expiration-time: 7