spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: public

encrypt:
  password: ${ENCRYPT_PASSWORD}

session:
  client-secret: ${SESSION_CLIENT_SECRET}
  access-token-expiration-time: 15
  refresh-token-expiration-time: 7

logging:
  level:
    root: INFO
    com.tourism: INFO
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework: INFO
  file:
    name: /var/log/tourism-app.log
    max-size: 10MB
    max-history: 10